### ISSUE TITLE
Спасибо большое!

### ISSUE THREAD

**Issue by benzlokzik** [vyragosa/OOP-exam-questions#1]
Спасибо за крутую работу. К слову, пр принимаются? Могу в коде в некоторых местах подправить кое-что, там есть недочёты некоторые с * и &

**Comment by vyragosa** [comment]
Спасибо за отзыв! Я поправлю. Там ещё с сигналами не так. Имеются ввиду именно сигналы как в курсовой

**Comment by benzlokzik** [comment]
> Спасибо за отзыв! Я поправлю. Там ещё с сигналами не так. Имеются ввиду именно сигналы как в курсовой

Хорошо, спасибо)
